sudo: required
services:
  - docker

before_install:
  - docker build -t robggarcia84/docker-react-rob -f Dockerfile.dev .

script:
  - docker run -e CI=true robggarcia84/docker-react-rob npm run test



