version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: robggarcia84/react-app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: robggarcia84/react-app    
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
      